version: '3.8'
services:
    hub:
        image: selenium/hub
        container_name: selenium_hub
        ports:
          - "4444:4444"
        environment:
          GRID_MAX_SESSION: 16
          GRID_BROWSER_TIMEOUT: 3000
          GRID_TIMEOUT: 3000
    
    chrome:
        image: selenium/node-chrome
        container_name: selenium_node_chrome
        depends_on:
          - hub
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
          NODE_MAX_SESSION: 4
          NODE_MAX_INSTANCES: 4
        volumes:
          - ./chrome:/dev/shm
          - ./chrome_tmp:/tmp
        ports:
          - "9001:5900"
        links:
          - hub